version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  aws-ecs: circleci/aws-ecs@3.2.0

executors:
  custom:
    machine:
      image: ubuntu-2404:2024.05.1
    resource_class: xlarge

jobs:
  build:
    docker:
      - image: cimg/node:20.9.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          name: "Restore Package Cache"
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: "Install dependencies"
          command: yarn --frozen-lockfile
      - save_cache:
          name: "Save Package Cache"
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: "Run build"
          command: npm run build

workflows:
  run-pipeline:
    jobs:
      - build

      # Build and push image to ECR
      - aws-ecr/build-and-push-image:
          requires:
            - build
          executor: custom
          repo: taskforce-connector
          region: eu-north-1
          tag: ${CIRCLE_BRANCH},${CIRCLE_BRANCH}-<< pipeline.number >>,${CIRCLE_BRANCH}-<< pipeline.number >>-${CIRCLE_SHA1}
          context: aws-account
          extra-build-args: '--build-arg=NPM_TOKEN=${NPM_TOKEN}'
          filters:
            branches:
              only:
                - master

      # Pre API update
      - aws-ecs/deploy-service-update:
          cluster: "step-shared-cluster"
          family: "pre-api-taskforce-connector"
          service-name: "pre-api-taskforce-connector-service"
          container-env-var-updates: container=pre-api-taskforce-connector-container,name=STEP_VERSION,value=${CIRCLE_BRANCH}-<< pipeline.number >>-${CIRCLE_SHA1}
          container-image-name-updates: container=pre-api-taskforce-connector-container,tag=${CIRCLE_BRANCH}-<< pipeline.number >>-${CIRCLE_SHA1}
          enable-circuit-breaker: true
          force-new-deployment: true
          context: aws-account
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only:
                - master

      # Pre indexer update
      - aws-ecs/deploy-service-update:
          cluster: "step-shared-cluster"
          family: "pre-indexer-taskforce-connector"
          service-name: "pre-indexer-taskforce-connector-service"
          container-env-var-updates: container=pre-indexer-taskforce-connector-container,name=STEP_VERSION,value=${CIRCLE_BRANCH}-<< pipeline.number >>-${CIRCLE_SHA1}
          container-image-name-updates: container=pre-indexer-taskforce-connector-container,tag=${CIRCLE_BRANCH}-<< pipeline.number >>-${CIRCLE_SHA1}
          enable-circuit-breaker: true
          force-new-deployment: true
          context: aws-account
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only:
                - master

      # Live API update
      - aws-ecs/deploy-service-update:
          cluster: "step-shared-cluster"
          family: "live-api-taskforce-connector"
          service-name: "live-api-taskforce-connector-service"
          container-env-var-updates: container=live-api-taskforce-connector-container,name=STEP_VERSION,value=${CIRCLE_BRANCH}-<< pipeline.number >>-${CIRCLE_SHA1}
          container-image-name-updates: container=live-api-taskforce-connector-container,tag=${CIRCLE_BRANCH}-<< pipeline.number >>-${CIRCLE_SHA1}
          enable-circuit-breaker: true
          force-new-deployment: true
          context: aws-account
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only:
                - master

      # Live indexer update
      - aws-ecs/deploy-service-update:
          cluster: "step-shared-cluster"
          family: "live-indexer-taskforce-connector"
          service-name: "live-indexer-taskforce-connector-service"
          container-env-var-updates: container=live-indexer-taskforce-connector-container,name=STEP_VERSION,value=${CIRCLE_BRANCH}-<< pipeline.number >>-${CIRCLE_SHA1}
          container-image-name-updates: container=live-indexer-taskforce-connector-container,tag=${CIRCLE_BRANCH}-<< pipeline.number >>-${CIRCLE_SHA1}
          enable-circuit-breaker: true
          force-new-deployment: true
          context: aws-account
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only:
                - master
